// packages/vue/src/components/ConnectButton.vue
<script setup lang="ts">
import { useConnect, useDialog } from "../composables"

const emit = defineEmits(["onConnect", "onDisconnect"])
const props = defineProps({
  dark: {
    type: Boolean,
    default: false,
  },
  style: {
    type: String,
    default: "",
  },
})

//@ts-ignore
const isICX = !!window.icx

const { open } = useDialog()

const onConnect = () => {
  emit("onConnect", {})
}

const onDisconnect = () => {
  emit("onDisconnect", {})
}

let { isConnected, disconnect, connect } = useConnect({
  // providers,
  onConnect,
  onDisconnect,
})
</script>

<template>
  <button v-if="isConnected" class="connect-button" @click="() => disconnect()">
    Disconnect
  </button>

  <button
    v-if="!isConnected"
    class="connect-button"
    @click="() => (isICX ? connect('icx') : open())"
  >
    Connect
  </button>
</template>

// packages/svelte/src/components/ConnectButton.svelte
<script lang="ts">
  import { useConnect, useDialog } from "../stores/index.ts"

  export const onConnect: () => void = () => {
  }
  export const onDisconnect: () => void = () => {
  }
  export const dark: boolean = false
  export const style: string = ""

  const isICX = !!window.icx
  const { open } = useDialog()
  const { isConnected, disconnect, connect } = useConnect({
    onConnect,
    onDisconnect,
  })
</script>

{#if $isConnected}
  <button style={style} class="disconnect-button" on:click={() => disconnect()}>
    Logout
  </button>
{/if}

{#if !$isConnected}
  <button style={style} class="connect-button" on:click={() => isICX ? connect("icx") : open()}>
    Connect Wallet
  </button>
{/if}
